import type { User, Company, Department, Project, SubProject, SOP, Notification, ChatRoom, TimeEntry } from "./types"

export const mockCompany: Company = {
  id: "comp_1",
  name: "TechFlow Solutions",
  companyCode: "TFS2024",
  logo: "/generic-company-logo.png",
  trialEndsAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  isActive: true,
  createdAt: new Date().toISOString(),
  plan: "trial",
}

export const mockUsers: User[] = [
  {
    id: "user_1",
    email: "john@techflow.com",
    name: "John Anderson",
    role: "company",
    companyId: "comp_1",
    avatar: "/professional-man-avatar.png",
    department: "Management",
    position: "CEO",
    phone: "+1 234 567 890",
    joinDate: "2024-01-15",
    points: 2500,
  },
  {
    id: "user_2",
    email: "sarah@techflow.com",
    name: "Sarah Mitchell",
    role: "qc_admin",
    companyId: "comp_1",
    avatar: "/professional-woman-avatar.png",
    department: "Engineering",
    position: "QC Lead",
    phone: "+1 234 567 891",
    joinDate: "2024-02-01",
    isLead: true,
    points: 1850,
  },
  {
    id: "user_3",
    email: "mike@techflow.com",
    name: "Mike Chen",
    role: "user",
    companyId: "comp_1",
    avatar: "/asian-man-avatar.png",
    department: "Engineering",
    position: "Senior Developer",
    phone: "+1 234 567 892",
    joinDate: "2024-02-15",
    points: 1420,
  },
  {
    id: "user_4",
    email: "emma@techflow.com",
    name: "Emma Wilson",
    role: "user",
    companyId: "comp_1",
    avatar: "/woman-with-glasses-avatar.png",
    department: "Design",
    position: "UI/UX Designer",
    phone: "+1 234 567 893",
    joinDate: "2024-03-01",
    isLead: true,
    points: 1680,
  },
  {
    id: "user_5",
    email: "alex@techflow.com",
    name: "Alex Rodriguez",
    role: "user",
    companyId: "comp_1",
    avatar: "/hispanic-man-avatar.png",
    department: "Marketing",
    position: "Marketing Manager",
    phone: "+1 234 567 894",
    joinDate: "2024-03-15",
    points: 980,
  },
  {
    id: "user_6",
    email: "lisa@techflow.com",
    name: "Lisa Thompson",
    role: "qc_admin",
    companyId: "comp_1",
    avatar: "/professional-woman-short-hair-avatar.jpg",
    department: "Quality",
    position: "QC Manager",
    phone: "+1 234 567 895",
    joinDate: "2024-04-01",
    points: 1520,
  },
]

export const mockDepartments: Department[] = [
  { id: "dept_1", name: "Engineering", color: "#2563eb", leadId: "user_2", memberCount: 12, createdAt: "2024-01-15" },
  { id: "dept_2", name: "Design", color: "#8b5cf6", leadId: "user_4", memberCount: 6, createdAt: "2024-01-15" },
  { id: "dept_3", name: "Marketing", color: "#10b981", leadId: "user_5", memberCount: 8, createdAt: "2024-01-15" },
  {
    id: "dept_4",
    name: "Quality Assurance",
    color: "#f59e0b",
    leadId: "user_6",
    memberCount: 4,
    createdAt: "2024-02-01",
  },
  { id: "dept_5", name: "Operations", color: "#ec4899", memberCount: 5, createdAt: "2024-02-15" },
]

export const mockProjects: Project[] = [
  {
    id: "proj_1",
    name: "Mobile App Redesign",
    description: "Complete redesign of the mobile application with new UI/UX patterns and improved performance",
    budget: 150000,
    status: "in_progress",
    startDate: "2024-06-01",
    endDate: "2024-12-31",
    teamIds: ["user_2", "user_3", "user_4"],
    leadId: "user_2",
    progress: 65,
    createdAt: "2024-05-15",
  },
  {
    id: "proj_2",
    name: "API Integration Platform",
    description: "Building a comprehensive API integration platform for third-party services",
    budget: 80000,
    status: "in_progress",
    startDate: "2024-07-01",
    endDate: "2024-11-30",
    teamIds: ["user_3", "user_6"],
    leadId: "user_3",
    progress: 45,
    createdAt: "2024-06-20",
  },
  {
    id: "proj_3",
    name: "Marketing Campaign 2024",
    description: "Q4 marketing campaign including digital ads, content creation, and social media strategy",
    budget: 50000,
    status: "planning",
    startDate: "2024-10-01",
    endDate: "2024-12-31",
    teamIds: ["user_5"],
    leadId: "user_5",
    progress: 15,
    createdAt: "2024-09-01",
  },
]

export const mockSubProjects: SubProject[] = [
  {
    id: "sub_1",
    projectId: "proj_1",
    name: "User Research & Analysis",
    description: "Conduct user interviews and analyze current app usage patterns",
    assigneeId: "user_4",
    status: "done",
    priority: "high",
    points: 150,
    dueDate: "2024-07-15",
    createdAt: "2024-06-01",
  },
  {
    id: "sub_2",
    projectId: "proj_1",
    name: "Wireframe Design",
    description: "Create wireframes for all main app screens",
    assigneeId: "user_4",
    status: "done",
    priority: "high",
    points: 200,
    dueDate: "2024-08-01",
    createdAt: "2024-06-15",
  },
  {
    id: "sub_3",
    projectId: "proj_1",
    name: "Frontend Development",
    description: "Implement the new UI components in React Native",
    assigneeId: "user_3",
    status: "in_progress",
    priority: "high",
    points: 350,
    dueDate: "2024-10-15",
    createdAt: "2024-08-01",
  },
  {
    id: "sub_4",
    projectId: "proj_1",
    name: "Backend API Updates",
    description: "Update backend APIs to support new app features",
    assigneeId: "user_2",
    status: "in_progress",
    priority: "medium",
    points: 250,
    dueDate: "2024-10-01",
    createdAt: "2024-08-15",
  },
  {
    id: "sub_5",
    projectId: "proj_2",
    name: "API Gateway Setup",
    description: "Set up the main API gateway infrastructure",
    assigneeId: "user_3",
    status: "done",
    priority: "urgent",
    points: 180,
    dueDate: "2024-07-30",
    createdAt: "2024-07-01",
  },
  {
    id: "sub_6",
    projectId: "proj_2",
    name: "OAuth Integration",
    description: "Implement OAuth 2.0 for third-party authentication",
    assigneeId: "user_6",
    status: "in_progress",
    priority: "high",
    points: 220,
    dueDate: "2024-09-15",
    createdAt: "2024-08-01",
  },
]

export const mockSOPs: SOP[] = [
  {
    id: "sop_1",
    title: "Onboarding Process Guide",
    description: "Complete guide for new employee onboarding procedures",
    type: "video",
    url: "/onboarding-video-thumbnail.jpg",
    thumbnailUrl: "/onboarding-video-thumbnail.jpg",
    status: "approved",
    createdBy: "user_2",
    approvedBy: "user_1",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-15",
    category: "HR",
  },
  {
    id: "sop_2",
    title: "Code Review Guidelines",
    description: "Standard procedures for conducting code reviews",
    type: "pdf",
    url: "/docs/code-review.pdf",
    status: "approved",
    createdBy: "user_3",
    approvedBy: "user_2",
    createdAt: "2024-07-01",
    updatedAt: "2024-07-10",
    category: "Engineering",
  },
  {
    id: "sop_3",
    title: "Design System Documentation",
    description: "Comprehensive design system and component library docs",
    type: "link",
    url: "https://design.techflow.com",
    status: "approved",
    createdBy: "user_4",
    approvedBy: "user_2",
    createdAt: "2024-07-15",
    updatedAt: "2024-07-20",
    category: "Design",
  },
  {
    id: "sop_4",
    title: "Security Protocols Training",
    description: "Training video for company security protocols",
    type: "video",
    url: "/security-training-video.jpg",
    thumbnailUrl: "/security-training-video.jpg",
    status: "pending",
    createdBy: "user_6",
    createdAt: "2024-09-01",
    updatedAt: "2024-09-01",
    category: "Security",
  },
  {
    id: "sop_5",
    title: "Brand Guidelines",
    description: "Official brand guidelines and assets",
    type: "image",
    url: "/brand-guidelines-concept.png",
    status: "pending",
    createdBy: "user_5",
    createdAt: "2024-09-10",
    updatedAt: "2024-09-10",
    category: "Marketing",
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "notif_1",
    userId: "user_1",
    title: "New SOP Pending Approval",
    message: "Security Protocols Training video is awaiting your approval",
    type: "warning",
    read: false,
    link: "/dashboard/sops",
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "notif_2",
    userId: "user_1",
    title: "Project Milestone Reached",
    message: "Mobile App Redesign has reached 65% completion",
    type: "success",
    read: false,
    link: "/dashboard/projects/proj_1",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "notif_3",
    userId: "user_1",
    title: "New Team Member",
    message: "Lisa Thompson has joined the Quality Assurance department",
    type: "info",
    read: true,
    link: "/dashboard/departments",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "notif_4",
    userId: "user_1",
    title: "Trial Ending Soon",
    message: "Your free trial ends in 3 days. Upgrade to continue.",
    type: "warning",
    read: false,
    link: "/dashboard/settings/billing",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
]

export const mockChatRooms: ChatRoom[] = [
  {
    id: "room_1",
    projectId: "proj_1",
    name: "Mobile App Team",
    memberIds: ["user_1", "user_2", "user_3", "user_4"],
    hasQcAdmin: true,
    createdAt: "2024-06-01",
  },
  {
    id: "room_2",
    projectId: "proj_2",
    name: "API Platform Team",
    memberIds: ["user_2", "user_3", "user_6"],
    hasQcAdmin: true,
    createdAt: "2024-07-01",
  },
]

export const mockTimeEntries: TimeEntry[] = [
  {
    id: "time_1",
    userId: "user_3",
    projectId: "proj_1",
    subProjectId: "sub_3",
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    endTime: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    duration: 7200,
    screenshots: ["/screenshot-1.png", "/screenshot-2.png"],
    description: "Working on navigation components",
  },
  {
    id: "time_2",
    userId: "user_4",
    projectId: "proj_1",
    subProjectId: "sub_2",
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    endTime: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    duration: 10800,
    screenshots: ["/design-screenshot.jpg"],
    description: "Finalizing wireframes for settings page",
  },
]
